### PR TITLE
looks better

### PR DESCRIPTION
**Pull request by goknsh**

### CODE REVIEW

**Comment by kbrsh** [comment]
The text isn't visible 😕

**Comment by goknsh** [comment]
realized that that's why i delete the repo

**Comment by kbrsh** [comment]
👍

**Comment by goknsh** [comment]
I tried to fix it such that the "sparks" would be seen behind the h1 and p but it would not work.
I basically suck at CSS (check out Cobra on mobile) so I just gave up.

**Comment by kbrsh** [comment]
Yeah, I actually didn't really like the sparks thing, so I just removed it a couple minutes ago.

**Comment by goknsh** [comment]
oh ok 👍

**Comment by goknsh** [comment]
but in theory, it should work this should work

``` css
body {
    background-color: black;
}
h1,
p {
    background-color: transparent;
}
```

**Pull request closed without merging**
